### ISSUE TITLE
Syntax error fix

### ISSUE THREAD

**Issue by MattMellifont** [sasever/SQLPoolsTools#3]
FYI - Great article, very helpful in my quest to figure out our performance problems. I found a slight bug in one of the scripts (due to synapses caps sensitivity, thorws a bound error). The query is this one from section 1.2
ERROR when run = 
> Msg 4104, Level 16, State 1, Line 96
> The multi-part identifier "C.system_type_id" could not be bound.

FIX =  
- this line
- INNER JOIN sys.types ty ON C.system_type_id = ty.system_type_id 
- needs to not be a capital C, needs to be lower case, throws binding issue and the table is set as 'c', therefore change required is
- INNER JOIN sys.types ty ON c.system_type_id = ty.system_type_id 

`SELECT
  DISTINCT
  t.object_id,
  s.name AS SchemaName,
  t.name AS TableName,
  t.Is_external,
  tdp.distribution_policy_desc AS distributionPolicyDesc,
  CASE WHEN cdp.distribution_ordinal = 1 THEN c.name ELSE NULL END AS DistCol,
  CASE WHEN cdp.distribution_ordinal = 1 THEN ty.name ELSE NULL END AS DistColDataType,
  CASE WHEN cdp.distribution_ordinal = 1 THEN c.max_length ELSE NULL END DistColDataLength,
  CASE WHEN cdp.distribution_ordinal = 1 THEN c.precision ELSE NULL END DistColDataPrecision,
  CASE WHEN cdp.distribution_ordinal = 1 THEN c.scale ELSE NULL END DistColDataScale,
  i.type_desc AS StorageType,
  CASE WHEN count(p.rows) > 1 THEN 'YES' ELSE 'NO' END AS IsPartitioned,
  count(p.rows) AS NumPartitions,
  sum(p.rows) AS NumRows
FROM
  sys.tables AS t
  INNER JOIN sys.schemas AS s ON t.schema_id = s.schema_id
  INNER JOIN sys.pdw_table_distribution_properties AS tdp ON t.object_id = tdp.object_id
  INNER JOIN sys.columns AS c ON t.object_id = c.object_id
  INNER JOIN sys.types ty ON C.system_type_id = ty.system_type_id
  INNER JOIN sys.pdw_column_distribution_properties AS cdp ON c.object_id = cdp.object_id
  AND c.column_id = cdp.column_id
  INNER JOIN sys.partitions p ON t.object_id = p.object_id
  INNER JOIN sys.indexes i ON t.object_id = i.object_id
WHERE 1=1
  AND (
    tdp.distribution_policy_desc <> 'HASH'
    OR cdp.distribution_ordinal = 1
  )
  AND i.index_ID < 2
  AND is_external = '0'
  AND ty.name != 'sysname'
GROUP BY
    t.object_id,  s.name,  t.name,  tdp.distribution_policy_desc,
    cdp.distribution_ordinal,  c.name,  i.type_desc,  Is_external,  ty.Name
	,c.max_length, c.precision, c.scale
UNION
SELECT
  t.object_id,
  s.name AS SchemaName,
  t.name AS TableName,
  Is_external,
  NULL AS distributionPolicyDesc,
  NULL AS DistColDataType,
  NULL AS DistCol,
  NULL AS DistColDataLength,
  NULL AS DistColDataPrecision,
  NULL AS DistColDataScale,
  'HADOOP' StorageType,
  'NO' AS IsPartitioned,
  0 AS NumPartitions,
  0 AS NumRows
FROM
  sys.tables AS t
  INNER JOIN sys.schemas AS s ON t.schema_id = s.schema_id
WHERE
  Is_External = '1'`

**Comment by sasever** [comment]
Thanks @MattMellifont , interesting that we did not hit this with prev usage. Sorry for noticing your issue late, will be fixing by mid December.

**Comment by sasever** [comment]
fixed already in Jan forgot to close the issue
